version: "3.5"

services:
  chatserver:
    image: node:14.18
    #build: ./compose/node
    volumes: 
      - ./volume/node:/home/node/work
    ports:
      - 9200:3000
    restart: always
    tty: true